version: '3.8'

networks:
  elk:
    name: elk

services:
  db: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    volumes:
      - ./:/sqlserver
    environment:
      - SA_PASSWORD=Teste@123
      - ACCEPT_EULA=Y
    networks: 
        - elk
